-- Seed opportunities data
INSERT INTO public.opportunities (title, description, full_description, deadline, location, modality, price, opportunity_type, education_levels, tags, women_eligibility, acceptance_rate, experience_required, requirements, organization, application_url)
VALUES
  (
    'Google Women Techmakers Scholarship',
    'Support women pursuing degrees in computer science and technology.',
    'The Women Techmakers Scholarship is designed to help aspiring computer scientists excel in technology and become leaders in the field. The scholarship provides financial support, access to a retreat, and a network of peers and mentors.',
    '2026-04-15 23:59:59+00',
    'Global',
    'hybrid',
    'free',
    'scholarship',
    ARRAY['undergraduate', 'graduate'],
    ARRAY['STEM', 'AI', 'Research'],
    'women_only',
    '15%',
    'Intermediate',
    ARRAY['Currently enrolled in a degree program', 'Strong academic background', 'Demonstrated leadership'],
    'Google',
    'https://www.womentechmakers.com/scholars'
  ),
  (
    'MIT Summer Research Program (MSRP)',
    'Research experience for underrepresented students in STEM fields.',
    'MSRP provides undergraduates with the opportunity to conduct research in an MIT laboratory under the guidance of experienced faculty. Participants receive housing, a meal plan, and a stipend.',
    '2026-02-01 23:59:59+00',
    'Cambridge, MA, USA',
    'in_person',
    'free',
    'research',
    ARRAY['undergraduate'],
    ARRAY['STEM', 'Research'],
    'open',
    '10%',
    'Beginner',
    ARRAY['Enrolled in an accredited university', 'Completed at least one year of college', 'U.S. citizen or permanent resident'],
    'MIT',
    'https://oge.mit.edu/msrp/'
  ),
  (
    'Echoing Green Fellowship',
    'Funding and support for social entrepreneurs launching new ventures.',
    'Echoing Green seeks emerging leaders with bold ideas for social change. Fellows receive seed funding, leadership development, and access to a global network of social entrepreneurs.',
    '2026-05-01 23:59:59+00',
    'Global',
    'virtual',
    'free',
    'fellowship',
    ARRAY['undergraduate', 'graduate', 'professional'],
    ARRAY['Entrepreneurship', 'Social Impact'],
    'open',
    '1%',
    'Advanced',
    ARRAY['Innovative idea for social change', 'Full-time commitment to venture', 'Demonstrated leadership'],
    'Echoing Green',
    'https://echoinggreen.org/fellowship/'
  ),
  (
    'Climate Solutions Accelerator',
    'Support for young climate entrepreneurs building impactful startups.',
    'A 12-week intensive program for young entrepreneurs working on climate tech solutions. Participants receive mentorship, funding, and access to industry experts.',
    '2026-03-20 23:59:59+00',
    'San Francisco, CA',
    'hybrid',
    'free',
    'grant',
    ARRAY['undergraduate', 'graduate', 'gap_year'],
    ARRAY['Climate', 'Entrepreneurship', 'Social Impact'],
    'women_preferred',
    '8%',
    'Intermediate',
    ARRAY['Working prototype or MVP', 'Team of 2-4 members', 'Climate-focused solution'],
    'Climate Tech Foundation',
    'https://climatetechfoundation.org/accelerator'
  ),
  (
    'AI Research Internship at OpenAI',
    'Hands-on experience in cutting-edge AI research and development.',
    'Work alongside world-class researchers on projects that push the boundaries of artificial intelligence. Interns contribute to real research projects and publications.',
    '2026-04-30 23:59:59+00',
    'San Francisco, CA',
    'in_person',
    'paid',
    'internship',
    ARRAY['undergraduate', 'graduate'],
    ARRAY['AI', 'Research', 'STEM'],
    'open',
    '5%',
    'Advanced',
    ARRAY['Strong programming skills', 'Background in ML/AI', 'Published research (preferred)'],
    'OpenAI',
    'https://openai.com/careers/internships'
  ),
  (
    'Women in STEM Leadership Summit',
    'A week-long intensive program for emerging women leaders in STEM.',
    'Connect with industry leaders, develop leadership skills, and build a network of peers. The summit includes workshops, keynote speakers, and mentorship opportunities.',
    '2026-06-15 23:59:59+00',
    'New York, NY',
    'in_person',
    'free',
    'summer_program',
    ARRAY['high_school', 'undergraduate'],
    ARRAY['STEM', 'Social Impact'],
    'women_only',
    '20%',
    'Beginner',
    ARRAY['Currently enrolled in school', 'Interest in STEM fields', 'Personal statement'],
    'Women in STEM Foundation',
    'https://womeninstem.org/summit'
  ),
  (
    'Global Social Innovation Challenge',
    'Pitch competition for student-led social ventures.',
    'Present your social venture to a panel of judges for the chance to win funding and mentorship. Open to student teams from around the world.',
    '2026-03-01 23:59:59+00',
    'Global (Virtual Finals)',
    'virtual',
    'free',
    'grant',
    ARRAY['high_school', 'undergraduate', 'graduate'],
    ARRAY['Entrepreneurship', 'Social Impact'],
    'open',
    '12%',
    'Beginner',
    ARRAY['Student team of 2-5', 'Social impact focus', 'Video pitch submission'],
    'Global Innovation Foundation',
    'https://globalinnovation.org/challenge'
  ),
  (
    'Rhodes Scholarship',
    'Fully-funded postgraduate study at the University of Oxford.',
    'One of the oldest and most prestigious international scholarship programs. Covers all university and college fees, a personal stipend, and health insurance.',
    '2026-10-01 23:59:59+00',
    'Oxford, UK',
    'in_person',
    'free',
    'scholarship',
    ARRAY['undergraduate', 'graduate'],
    ARRAY['Research', 'Social Impact'],
    'open',
    '0.7%',
    'Advanced',
    ARRAY['Outstanding academic achievement', 'Leadership potential', 'Commitment to service'],
    'Rhodes Trust',
    'https://www.rhodeshouse.ox.ac.uk/scholarships/'
  );
