-- FoundHer Seed Data
-- Sample opportunities for the platform

INSERT INTO public.opportunities (title, organization, description, category, url, deadline, location, is_remote, funding_amount, eligibility, tags, requirements, benefits, is_featured)
VALUES
  (
    'Women in Tech Scholarship',
    'Google',
    'A scholarship program designed to support women pursuing degrees in computer science, computer engineering, or a closely related technical field.',
    'scholarship',
    'https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-women',
    '2026-06-15',
    'Global',
    true,
    '$10,000 USD',
    'Women pursuing a degree in computer science or related technical field. Must be a full-time student.',
    ARRAY['technology', 'women in tech', 'computer science', 'engineering'],
    ARRAY['Full-time student', 'Minimum GPA of 3.0', 'Strong academic background'],
    ARRAY['$10,000 scholarship', 'Google retreat', 'Mentorship opportunities'],
    true
  ),
  (
    'Techstars Startup Weekend Women',
    'Techstars',
    'A 54-hour event where women entrepreneurs pitch ideas, form teams, and launch startups.',
    'competition',
    'https://www.techstars.com/communities/startup-weekend',
    '2026-04-20',
    'Latin America',
    false,
    'Up to $50,000 in prizes',
    'Women founders and aspiring entrepreneurs',
    ARRAY['entrepreneurship', 'startup', 'women founders', 'Latin America'],
    ARRAY['Business idea', 'Commitment for 54 hours'],
    ARRAY['Mentorship', 'Networking', 'Potential funding'],
    true
  ),
  (
    'Climate Tech Fellowship',
    'ClimateWorks Foundation',
    'A 12-month fellowship program for young women working on climate solutions.',
    'fellowship',
    'https://www.climateworks.org',
    '2026-05-01',
    'Remote',
    true,
    '$75,000 annual stipend',
    'Women aged 18-30 with demonstrated interest in climate tech',
    ARRAY['climate', 'sustainability', 'environment', 'technology'],
    ARRAY['Climate project portfolio', 'Letters of recommendation', 'Personal statement'],
    ARRAY['Full stipend', 'Mentorship', 'Conference attendance', 'Research funding'],
    true
  ),
  (
    'Women Founders Accelerator',
    'Y Combinator',
    'A specialized accelerator track for women-led startups.',
    'program',
    'https://www.ycombinator.com',
    '2026-03-31',
    'San Francisco, USA',
    false,
    '$500,000 investment',
    'Women-led startups with a working prototype',
    ARRAY['startup', 'investment', 'accelerator', 'women founders'],
    ARRAY['Working prototype', 'Full-time commitment', 'US-based or willing to relocate'],
    ARRAY['$500K investment', '3-month program', 'YC network access'],
    true
  ),
  (
    'Social Impact Grant for Young Women',
    'Echoing Green',
    'Grants for young women creating social enterprises that address critical issues.',
    'grant',
    'https://echoinggreen.org',
    '2026-07-15',
    'Global',
    true,
    '$80,000 over two years',
    'Women aged 18-35 with a social enterprise idea',
    ARRAY['social impact', 'entrepreneurship', 'nonprofit', 'community'],
    ARRAY['Social enterprise plan', 'Leadership experience', 'Community impact focus'],
    ARRAY['$80K funding', 'Leadership development', 'Global network'],
    false
  ),
  (
    'STEM Internship Program',
    'Microsoft',
    'Summer internship program for women in STEM fields.',
    'internship',
    'https://careers.microsoft.com',
    '2026-02-28',
    'Multiple Locations',
    false,
    'Competitive salary + housing',
    'Women enrolled in STEM programs at accredited universities',
    ARRAY['internship', 'technology', 'STEM', 'career'],
    ARRAY['Enrolled in STEM degree', 'Available for 12 weeks', 'Strong coding skills'],
    ARRAY['Competitive pay', 'Housing stipend', 'Mentorship', 'Return offer potential'],
    false
  ),
  (
    'Women in AI Research Grant',
    'Partnership on AI',
    'Research grants for women conducting AI ethics and safety research.',
    'grant',
    'https://partnershiponai.org',
    '2026-08-01',
    'Remote',
    true,
    '$50,000',
    'Women researchers in AI/ML fields',
    ARRAY['artificial intelligence', 'research', 'ethics', 'machine learning'],
    ARRAY['Research proposal', 'Academic affiliation', 'Published work in AI'],
    ARRAY['Research funding', 'Publication support', 'Conference sponsorship'],
    false
  ),
  (
    'Latina Founders Fund',
    'Kapor Capital',
    'Investment fund specifically for Latina founders in tech.',
    'grant',
    'https://www.kaporcapital.com',
    NULL,
    'United States',
    true,
    'Up to $250,000',
    'Latina women founding tech startups',
    ARRAY['Latina', 'investment', 'startup', 'diversity'],
    ARRAY['Tech startup', 'Latina founder or co-founder', 'US-based'],
    ARRAY['Investment', 'Mentorship', 'Network access'],
    true
  ),
  (
    'Women Who Code Mentorship',
    'Women Who Code',
    'Global mentorship program connecting women in tech.',
    'mentorship',
    'https://www.womenwhocode.com',
    NULL,
    'Remote',
    true,
    'Free',
    'Women working in or aspiring to work in technology',
    ARRAY['mentorship', 'technology', 'career development', 'networking'],
    ARRAY['Technology interest', 'Commitment to 6-month program'],
    ARRAY['1-on-1 mentorship', 'Skill workshops', 'Community events'],
    false
  ),
  (
    'FinTech Innovation Challenge',
    'Mastercard',
    'Competition for women developing innovative fintech solutions.',
    'competition',
    'https://www.mastercard.com',
    '2026-09-15',
    'Global',
    true,
    '$100,000 grand prize',
    'Women-led teams with fintech innovations',
    ARRAY['fintech', 'innovation', 'competition', 'finance'],
    ARRAY['Fintech solution prototype', 'Women-led team', 'Video pitch'],
    ARRAY['Cash prizes', 'Pilot program opportunity', 'Mastercard partnership'],
    false
  );

-- Note: Posts, groups, and other user-generated content will be created by users
-- through the application interface
